# remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-sitemap
#   - jekyll-remote-theme
#  - jekyll-last-modified-at
markdown: redcarpet 
redcarpet: 
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"] 
